server:
  port: 2525
spring:
  datasource:
    url: jdbc:mysql://localhost:1001/Fruit?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false

