version: '3.3'
services:
  FRUIT:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '1001:3306'
    volumes:
      - my-db:/var/lib/mysql
  adminer:
    image: dockette/adminer:full-php5
    ports:
      - '3003:8080'
volumes:
  my-db: